services:
    domain_driven_design.event_dispatcher:
        alias: domain_driven_design.event_dispatcher.default

    domain_driven_design.event_dispatcher.default:
        class: PhpDDD\DomainDrivenDesign\Event\EventDispatcher
