sudo: false

language: php

php:
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="2.6.*"
  - SYMFONY_VERSION="2.7.*"
  - SYMFONY_VERSION="2.8.*@dev"
  - SYMFONY_VERSION="3.0.x-dev as 2.8"

matrix:
  allow_failures:
    - env: SYMFONY_VERSION="2.8.*@dev"
    - env: SYMFONY_VERSION="3.0.x-dev as 2.8"
  fast_finish: true

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - composer selfupdate
  - composer config github-oauth.github.com $GITHUB_OAUTH_TOKEN
  # Remove unnecessary dev dependencies
  - composer remove  --no-update --dev phpmd/phpmd fabpot/php-cs-fixer phploc/phploc
  - composer require --no-update "symfony/config:${SYMFONY_VERSION}"
  - composer require --no-update "symfony/dependency-injection:${SYMFONY_VERSION}"
  - composer require --no-update "symfony/http-kernel:${SYMFONY_VERSION}"
  # For dev branches, need to specify the package dependencies
  - composer require --no-update "symfony/debug:${SYMFONY_VERSION}"
  - composer require --no-update "symfony/event-dispatcher:${SYMFONY_VERSION}"
  - composer require --no-update "symfony/filesystem:${SYMFONY_VERSION}"
  - composer require --no-update "symfony/http-foundation:${SYMFONY_VERSION}"

install:
  - composer update --no-interaction --prefer-dist

script:
  - phpunit
  - mkdir -p .autoload/composer && mv -v ./vendor/autoload.php ./.autoload/autoload.php && mv -v ./vendor/composer/!(installed.json) ./.autoload/composer

after_script:
  - mv -v ./.autoload/autoload.php ./vendor/autoload.php && mv -v ./.autoload/composer/* ./vendor/composer && rm -r .autoload
  - php vendor/bin/coveralls -v
